#!/usr/bin/env python3
"""Emit the first 0x1000 bytes of 80010008.self as a C const array header.

Purpose: remove target.self from the payload's critical path. GoldHEN's FTP server
dies on its first data command, so we cannot reliably place an 88 KB (or even 4 KB)
file on the console - but the payload is delivered over TCP, which works. Step 7
needs only the first 0x1000 bytes of the file (it copies exactly PAGE_SZ into the
module's staging page), so those bytes can simply live in the payload.

These bytes are from an *encrypted* SELF we already hold locally; nothing secret is
being embedded.
"""
import os

SRC = r'C:\Users\Kinan\Downloads\JV13.52\dec\1352\80010008.self'
DST = r'C:\Users\Kinan\Downloads\JV13.52\selfdec2\source\embed_hdr.h'

b = open(SRC, 'rb').read(0x1000)
assert len(b) == 0x1000, len(b)

with open(DST, 'w', encoding='utf-8') as f:
    f.write('/* GENERATED by gen_embed.py - do not edit.\n')
    f.write(' * First 0x1000 bytes of 80010008.self, so the payload does not depend on\n')
    f.write(' * target.self being staged over FTP. Step 7 copies exactly PAGE_SZ bytes\n')
    f.write(' * from this buffer into the module staging page. */\n')
    f.write('#ifndef EMBED_HDR_H\n#define EMBED_HDR_H\n\n')
    f.write('#define EMBED_HDR_SIZE 0x1000\n\n')
    f.write('static const unsigned char g_embed_hdr[EMBED_HDR_SIZE] = {\n')
    for off in range(0, len(b), 16):
        chunk = b[off:off + 16]
        f.write('  ' + ' '.join(f'0x{x:02x},' for x in chunk) + '\n')
    f.write('};\n\n#endif /* EMBED_HDR_H */\n')

print(f'wrote {DST}: {os.path.getsize(DST)} B for {len(b)} header bytes')
print('first 16 bytes:', b[:16].hex(' '))
print('magic check    :', b[:4], '(SELF magic is 0x1d3d154f little-endian: '
      f'{int.from_bytes(b[:4], "little"):#010x})')
